# SPDX-License-Identifier: GPL-2.0-only

networks:
  smo:
    external: true
    name: smo

services:
  grafana:
    image: $GRAFANA_IMAGE
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB2_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB2_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB2_TOKEN}
    external_links:
      - influxdb2
    ports:
      - '3000:3000' # Expose Grafana on port 3000
    volumes:
      - grafana-data:/var/lib/grafana # Mount the Grafana data directory
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      smo:
volumes:
  grafana-data:
